# ==========================================
# LumiTags Configuration File
# ==========================================

# The weight/priority of the prefix node in LuckPerms.
# Higher priority values take precedence.
prefix-weight: 500

# Permissions settings.
# You can customize these if you want to use existing permission nodes.
permissions:
  use: "lumitags.use"
  moderator: "lumitags.moderator"
  admin: "lumitags.admin"

# Console commands to execute when a lumitag action is taken.
# Placeholders: %player% (target player), %rank% (the rank nickname)
commands:
  on-set:
    - "broadcast &a%player%'s tag has been changed to %rank%!"
  on-off: []

# Transform
# You can define transformations to apply to the rank nickname before setting it.
# Supported transformations: uppercase, lowercase, capitalize, smallcaps, bold, italic, underline, strikethrough
transformations:
  - bold
  - smallcaps

# Customize messages sent to players and staff.
# Color codes (&) are supported.
messages:
  no-permission: "&cYou do not have permission to execute this command."
  no-permission-other: "&cYou don't have the permission to set other people's LumiTags!"
  
  invalid-format: |
    &cInvalid command format
    &7Command Usage:
    &b/lumitag set <Rank Name>
    &b/lumitag off
    
  invalid-format-moderator: |
    &cInvalid command format
    &7Command Usage:
    &b/lumitag set <Rank Name>
    &b/lumitag <Player> <Rank Name>
    &b/lumitag off

  rank-changed-self: "&aRank successfully changed!"
  rank-changed-other: "&a%player%'s Rank successfully changed!"
  
  rank-removed-self: "&cOld rank removed."
  rank-removed-other: "&cLumiTag removed for %player%."
  
  player-not-found: "&cPlayer '%player%' is not online or cannot be found."
  reload-success: "&aLumiTags configuration successfully reloaded."
